export const characters = [
  {
    id: "rafayel",
    name: "Rafayel",
    title: "Painter of the Deep",
    accent: "#FF6F91",
    accentSoft: "rgba(255,111,145,0.35)",
    blurb:
      "A moon-touched painter who trades in tides, temper, and unfinished canvases.",
    available: true,
  },
  {
    id: "zayne",
    name: "Zayne",
    title: "The Steady Hand",
    accent: "#7FB6D9",
    accentSoft: "rgba(127,182,217,0.3)",
    blurb: "Calm under pressure, precise in every word.",
    available: false,
  },
  {
    id: "xavier",
    name: "Xavier",
    title: "The Quiet Watch",
    accent: "#9CA9C4",
    accentSoft: "rgba(156,169,196,0.3)",
    blurb: "Says little, notices everything.",
    available: false,
  },
  {
    id: "sylus",
    name: "Sylus",
    title: "The Wildcard",
    accent: "#B24EE0",
    accentSoft: "rgba(178,78,224,0.3)",
    blurb: "Danger dressed as charm.",
    available: false,
  },
  {
    id: "caleb",
    name: "Caleb",
    title: "The Bright Wolf",
    accent: "#E8A15C",
    accentSoft: "rgba(232,161,92,0.3)",
    blurb: "Warm-hearted, wears his loyalty openly.",
    available: false,
  },
  {
    id: "vargo",
    name: "Vargo",
    title: "The Unwritten",
    accent: "#6FE0C0",
    accentSoft: "rgba(111,224,192,0.3)",
    blurb: "A story still being drafted.",
    available: false,
  },
];